### ISSUE TITLE
Document out of date

### ISSUE THREAD

**Issue by KevinYeti** [juhgiyo/EpServerEngine.cs#3]
hi, juhgiyo 
Great job for the engine.
I just want to know what is the concept of the Room class and how to use. The document seems to out of date.
Thank you for your reply.

**Comment by juhgiyo** [comment]
Hi
Room is server side operation. 
The reason, I have not updated the document is that I haven't really tested them heavily yet.
The idea is simple.
You can just call Join function with the name of the room (whatever you want to call for the room),
then you can call BroadcastToRoom from any socket within the room so you can deliver whatever packet you want to sockets within the room.

**Comment by KevinYeti** [comment]
That's really amazing and what I'm looking for.That's a good function at server side for a game. 
Should I connect all the clients to the server first if I want to call the Join function ?

**Comment by juhgiyo** [comment]
No, you don't have to connect all the clients to the server. One connection is good enough to create the room (When there is no client, then the room is automatically destroyed). You can join the room with other sockets, when the socket is connected to the server later on.

**Comment by KevinYeti** [comment]
OK~ thank you for fast reply. 
hoping your samples~
