### ISSUE TITLE
Cannot access a disposed object.

### ISSUE THREAD

**Issue by azzahrah** [juhgiyo/EpServerEngine.cs#4]
Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'. >   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
   at EpServerEngine.cs.IocpTcpServer.onAccept(IAsyncResult result) in d:\projects\c#\ServerGps\v1.0.0\EpServerEngine.cs\EpServerEngine.cs\ServerSide\IOCP\IocpTcpServer.cs:line 462

**Comment by juhgiyo** [comment]
Any more detail on the error?

**Comment by azzahrah** [comment]
This error fire when i try disconnect clients, then i try stop server....

**Comment by juhgiyo** [comment]
As it is handled by try-catch clause, you can just ignore the error.
The message is there just to inform that such exception is occurred.
The error is simple, you disconnected the client which is in the middle of connection to the server.
And when you stopped the server, the server stops the listening socket, and tries to clean up the client that is in connection.
As this client is already disconnected, it is already cleaned up, but the server tries to clean up as the listening socket is closed, which results accessing disposed object.

Simple word, you can ignore the error without any concern.
